### ISSUE TITLE
Plans on releasing the source code? The concept itself is awesome :)

### ISSUE THREAD

**Issue by jorgerance** [luisleo526/Leveraged-grid-trading-bot#2]

**Comment by luisleo526** [comment]
If you want the source code, you can tact me for discussion via email

**Comment by jorgerance** [comment]
No need for that :)

https://github.com/yehjames/Leveraged-grid-trading-bot

**Comment by jorgerance** [comment]
> If you want the source code, you can tact me for discussion via email

No need for that :)

https://github.com/yehjames/Leveraged-grid-trading-bot
